# NOTE: start using this file, THIS IS NOT FOR SENSITIVE DATA (PASSWORD, TOKEN, KEYS)
region            = "us-east-1"
vpc_name          = "Hesler-VPC"
vpc_cidr          = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
az                = "us-east-1a"
sg_name           = "Default-SG"
instance_name     = "Default-EC2"
ami_id            = "ami-0c02fb55956c7d316"
instance_type     = "t2.micro"
s3_bucket_name    = "default-project-bucket"
